---
- name: Fail when 'conga_aemdst_curl_url' is not defined.
  fail:
    msg: "Please define the url in variable: 'conga_aemdst_curl_url'"
  when: conga_aemdst_curl_url is none

- name: Fail when 'conga_aemdst_curl_expected_url' is not defined.
  fail:
    msg: "Please define the url in variable: 'conga_aemdst_curl_expected_url'"
  when: conga_aemdst_curl_expected_url is none

- name: "Build curl command line."
  curl_cmdline_helper:

- name: Debug conga_aemdst_curl_cmdline.
  debug:
    var: conga_aemdst_curl_cmdline
    verbosity: 1

- name: "Debug output."
  debug:
    msg:
      - "check redirect from: {{ conga_aemdst_curl_url }}"
      - "check redirect to  : {{ conga_aemdst_curl_expected_url }}"
      - "check for http code: {{ conga_aemdst_curl_cmdline.expected_http_code }}"
      - "Internal curl command:"
      - "{{ conga_aemdst_curl_cmdline.curl_internal_command }}"
      - "Debug curl command:"
      - "{{ conga_aemdst_curl_cmdline.curl_debug_command }}"

- name: "Executing curl"
  shell: "{{ conga_aemdst_curl_cmdline.curl_internal_command }}"
  register: curl_result
  delegate_to: "{{ conga_aemdst_curl_host }}"
  args:
    warn: false
  changed_when: false
  tags:
    - skip_ansible_lint

- name: "Parse curl result"
  set_fact:
    _actual_url: "{{ curl_result.stdout_lines[0] }}"
    _actual_http_code: "{{ curl_result.stdout_lines[1] }}"

# lazy test, expected url can be part of actual url
- name: "Assert that actual url matches expected url (lazy)"
  assert:
    that:
      - "{{ conga_aemdst_curl_expected_url in _actual_url }}"
    msg: >-
      The actual url does not match with expected url (lazy)
      expected: {{ conga_aemdst_curl_expected_url }}
      actual  : {{ _actual_url }}
  when: conga_aemdst_curl_expected_url_test_lazy

# non lazy test, exact match requested
- name: "Assert that actual url matches expected (strict)"
  assert:
    that:
      - "{{ conga_aemdst_curl_expected_url == _actual_url }}"
    msg: >-
      The actual url does not match with expected url (strict)
      expected: {{ conga_aemdst_curl_expected_url }}
      actual  : {{ _actual_url }}
  when: not conga_aemdst_curl_expected_url_test_lazy

- name: "Assert that actual response code matches {{ conga_aemdst_curl_cmdline.expected_http_code }}"
  assert:
    that:
      - "{{ conga_aemdst_curl_cmdline.expected_http_code }} == {{ _actual_http_code }}"
    msg: >-
      The actual http_code does not match with expected http_code
      expected: {{ conga_aemdst_curl_cmdline.expected_http_code }}
      actual  : {{ _actual_http_code }}
