- name: "Run aem-publish tests"
  include_tasks: aem-publish-tests.yml
  when: "'aem-publish' in conga_variants"

- name: "Run aem-author tests"
  include_tasks: aem-author-tests.yml
  when: "'aem-author' in conga_variants"
