- name: "Run aem-publish tests"
  static: no
  include: aem-publish-tests.yml
  when: "'aem-publish' in conga_variants"

- name: "Run aem-author tests"
  static: no
  include: aem-author-tests.yml
  when: "'aem-author' in conga_variants"